spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/FMH_DB
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
  flyway:
    locations: classpath:db/migration/dev
server:
  servlet:
    context-path: /fmh

logging.level.ru.iteco.fmh: debug

swagger:
  host: localhost